fix

diff --git a/.github/workflows/Runner-Ubuntu.yml b/.github/workflows/Runner-Ubuntu.yml
--- a/.github/workflows/Runner-Ubuntu.yml
+++ b/.github/workflows/Runner-Ubuntu.yml
@@ -57,8 +57,8 @@ jobs:
           base64 -d - <<< "${{ secrets.CLFCONFIG }}" > ~/.cloudflared/config.yml
           base64 -d - <<< "${{ secrets.CLFTUNNEL }}" > ~/.cloudflared/${{ secrets.TUNNEL_ID }}.json
           sed -i "s|test12341234\.freesites\.eu\.org|linux-ssh-${{ github.event.inputs.ID }}.dgbaodev.site|g" ~/.cloudflared/config.yml || { echo "Failed to rename hostname"; exit 1; }
-          cloudflared tunnel route dns linux-ssh "linux-ssh-${{ github.event.inputs.ID }}.dgbaodev.site"
-          cloudflared tunnel run linux-ssh
+          cloudflared tunnel route dns linux-ssh "linux-ssh-${{ github.event.inputs.ID }}.dgbaodev.site" > /dev/null 2>&1 || { echo "Failed to route dns"; exit 1; }
+          cloudflared tunnel run linux-ssh > /dev/null 2>&1 &
           pid_x=$!
           echo $pid_x | tee ~/cloudflared.pid > /dev/null
           rm -f ~/.cloudflared/config.yml ~/.cloudflared/cert.pem ~/.cloudflared/*.json
@@ -71,10 +71,10 @@ jobs:
       - name: Done
         if: always()
         run: |
-          if sudo [ -f ~/cloudflared.pid ]; then
-            sudo kill $(sudo cat ~/cloudflared.pid) && echo "Cloudflared stopped successfully" || echo "Failed to stop cloudflared"
-            sudo rm -f ~/cloudflared.pid
-            sudo rm -rf ~/.cloudflared
+          if [ -f ~/cloudflared.pid ]; then
+            kill $(cat ~/cloudflared.pid) && echo "Cloudflared stopped successfully" || echo "Failed to stop cloudflared"
+            rm -f ~/cloudflared.pid
+            rm -rf ~/.cloudflared
           else
             echo "No PID file found."
           fi
